import './globals.css'
import { Inter } from 'next/font/google'
// import { ClerkProvider, SignIn, SignUp, SignedOut  } from '@clerk/nextjs'
import Navbar from '@/Components/Navbar'
import Desc_sec from '@/Section/Desc_sec'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dine Mart',
  description: 'Generated by create next app',
  Image:"/Hsec/event1.webp"
}
const publicPages = []
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      {/* <ClerkProvider>
        <SignedOut> */}
      <body className='max-w-[80rem] min-w-[50rem] mx-auto'>
      {/* @ts-ignore */}
        <Navbar/>
        {children}
        <Desc_sec/>
        
        </body>
        {/* </SignedOut>
        </ClerkProvider> */}
    </html>
    
  )
}
